# Generated by Django 3.0.3 on 2020-03-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='form_to',
            new_name='from_to',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('name', 'video_type', 'from_to', 'nation')},
        ),
    ]
